#property strict
#property version   "1.0.25"
#define SCENOVA_EA_VERSION "1.0.25"
#define SCENOVA_PRODUCT_VERSION "1.0.25"
#define SCENOVA_RUNTIME_CONTRACT "RACE_VOLUME_10S_ROLLOVER_V1"
#property description "MT5 SaaS Fast Basket Engine - Cloud/Local"
#property description "Use Demo and forward testing before live trading."

// SCENOVA STRUCTURAL MODULES: order-preserving source partition only.
// Runtime behavior is preserved byte-for-byte when these includes are expanded.
// Generated by scripts/refactor-mq5-structural.py; do not reorder the parts.
#include "FastBasketBot.Part01.mqh"
#include "FastBasketBot.Part02.mqh"
#include "FastBasketBot.Part03.mqh"
#include "FastBasketBot.Part04.mqh"
#include "FastBasketBot.Part05.mqh"
#include "FastBasketBot.Part06.mqh"
#include "FastBasketBot.Part07.mqh"
#include "FastBasketBot.Part08.mqh"
#include "FastBasketBot.Part09.mqh"
