$ErrorActionPreference = 'Stop'
function Read-Text([string]$path){ if(-not (Test-Path $path)){throw "Missing $path"}; [System.IO.File]::ReadAllText((Resolve-Path $path)) }
function Block([string]$text,[string]$sig){ $s=$text.IndexOf($sig); if($s -lt 0){throw "Missing $sig"}; $b=$text.IndexOf("{",$s); $d=0; for($i=$b;$i -lt $text.Length;$i++){ if($text[$i] -eq "{"){$d++} elseif($text[$i] -eq "}"){$d--; if($d -eq 0){return $text.Substring($s,$i-$s+1)}}}; throw "Unclosed $sig" }
function Need([string]$text,[string]$needle,[string]$message){ if(-not $text.Contains($needle)){throw $message} }
function Forbid([string]$text,[string]$needle,[string]$message){ if($text.Contains($needle)){throw $message} }

$ea=Read-Text 'mt5/FastBasketBot.mq5'
$vec=Read-Text 'mt5/include/AutoVectorEdgeLive.mqh'
$release=Read-Text 'apps/api/src/release-version.ts'
$manage=Block $ea 'bool AutoManageOpenBasket('
$wrong=Block $ea 'bool AutoWrongDirectionConfirmed('
$precision=Block $ea 'int AutoPrecisionDirection(double momentum)'
$risk=Block $ea 'bool AutoRiskBudgetAllows('
$zoneIntegrity=Block $ea 'bool AutoZoneStructureIntact(int direction)'
$send=Block $ea 'bool SendMarketOrder(int direction)'
$dynamic=Block $ea 'void ManageDynamicProtection()'
$onTick=Block $ea 'void OnTick()'

Need $ea '#define AUTO_POLICY "AUTO_BALANCED_EXIT"' 'AUTO marker missing'
Need $ea '#define AUTO_EXIT_CYCLE_GRACE_SECONDS 30' 'AUTO loss exit must have 30-second cycle grace'
Need $ea '#define AUTO_EXIT_LAST_FILL_GRACE_SECONDS 15' 'AUTO loss exit must have post-fill grace'
Need $ea '#define AUTO_EXIT_CONFIRM_SECONDS 10' 'normal AUTO reversal must persist'
Need $ea '#define AUTO_EXIT_SEVERE_CONFIRM_SECONDS 6' 'severe AUTO reversal must still persist'
Need $wrong 'atrM5*0.32' 'AUTO must reject shallow pullback noise'
Need $wrong 'g_trendM5==opposite' 'AUTO must require completed M5 reversal evidence'
Need $wrong 'g_emaTrendM5==opposite' 'AUTO must require EMA structure evidence'
Need $wrong 'g_autoExitCandidateSince=now' 'AUTO must arm before soft close'
Need $wrong 'g_autoExitCandidatePeakAdverse*0.70' 'AUTO must cancel on meaningful rebound'
Need $wrong 'AutoVectorEdgeLiveExitLost(direction)' 'Vector edge loss must only confirm balanced exit'
Forbid $manage 'progress<=-atrPoints*0.18' 'obsolete fast 0.18 ATR close remains'
Need $manage 'EffectiveBasketLossLimit()' 'hard basket loss must bypass soft grace'
Need $manage 'AUTO_EXIT_CANDIDATE' 'candidate must pause new AUTO adds'
Forbid $manage 'SmartProfitReversalDetected(' 'AUTO may not market-close profits on reversal'
Forbid $manage 'AutoProfitGivebackDetected(' 'AUTO may not market-close profits on giveback'
Forbid $manage 'AUTO_EARLY_PROFIT_REVERSAL' 'AUTO may not close tiny profits early'
Forbid $manage 'AUTO_EARLY_PROFIT_GIVEBACK' 'AUTO may not close tiny profits early'
Need $ea 'targetOpenedAt' 'restart migration must recover the oldest AUTO position target'
Need $send 'g_autoBasketTargetPrice' 'AUTO add must inherit canonical TP'
Need $send 'request.tp=autoPlan.tpPrice;' 'AUTO Broker TP must be on every new AUTO order'
Need $send 'g_autoBasketStopPrice' 'AUTO add must inherit canonical/tighter SL'
Need $dynamic 'desiredTP=NormalizeTargetPriceToTick(g_autoBasketTargetPrice,direction);' 'Dynamic engine must keep canonical AUTO TP broker-tick aligned when no hard money target is active'
Forbid $dynamic 'clearAutoMoneyTargetTP' 'AUTO Broker TP must not be cleared'
Need $dynamic 'progressToTp>=distanceToTp*0.80' 'AUTO 80 percent TP progress trigger missing'
Need $dynamic 'openPrice+direction*distanceToTp*0.50' 'AUTO 50 percent SL lock missing'
Need $precision 'AutoApplyNoIncreaseLotCap(selected);' 'AUTO fixed-Lot contract must be applied to every selected side'
Need $precision 'bool relaxedFirstFour=count<4;' 'AUTO positions 1-4 must remain opportunity-first'
Need $precision 'if(!vectorLiveAllowed && !relaxedFirstFour)' 'Vector Edge hard veto must start from AUTO position 5'
Need $zoneIntegrity 'breakTolerance=atrPrice*0.18' 'AUTO first-four Zone break tolerance missing'
Need $risk 'if(existingCount<4)' 'AUTO hidden percentage risk gate must not starve positions 1-4'
Need $risk 'EffectiveBasketLossLimit()' 'AUTO first-four risk must use the visible Basket Loss setting'
Need $risk 'AUTO_VISIBLE_BASKET_RISK_LIMIT' 'AUTO visible Basket Loss rejection reason missing'
Need $send 'g_executionStatus="AUTO_PRICE_MOVED_REEVALUATE";' 'AUTO fast-price re-plan telemetry must remain visible'
Need $send 'AutoPlanPrices(autoPlan,g_autoLevels);' 'AUTO fast-price move must re-plan structure SL/TP once'
Need $ea 'side.plannedLot=NormalizeTradeVolume(g_lot);' 'AUTO must use the configured Lot directly'
Need $ea 'Fixed-Lot contract: every new AUTO order uses the configured AUTO Lot.' 'AUTO fixed-Lot ownership marker missing'
Forbid $ea 'side.plannedLot=NormalizeTradeVolume(g_lot*sizeFactor);' 'AUTO must not silently scale Lot by confidence/RR'
Need $precision 'AutoRiskBudgetAllows(selected,count,riskReason)' 'AUTO risk ceiling must block instead of resizing Lot'
Need $onTick 'autoNoRescue' 'AUTO must skip new Rescue engine'
Need $ea 'bool g_rescueEnabled = false;' 'Adaptive Rescue must default disabled globally'
Need $ea 'g_executionStatus="RESCUE_DISABLED";' 'Recovery hedge execution must stay disabled'
Need $vec 'SELECTED_SIDE_WARMUP_ALLOW' 'Vector warmup must be selected-side based'
Need $vec 'AutoVectorEdgeLiveExitLost' 'Vector exit confirmation helper missing'
Need $vec 'never a direct close and never a lot-sizing signal' 'Vector Kelly/risk must not increase customer Lot'
$eaVersionMatch = [regex]::Match($ea, '#property\s+version\s+"([^"]+)"')
$releaseVersionMatch = [regex]::Match($release, 'DEFAULT_EA_VERSION\s*=\s*"([^"]+)"')
if(-not $eaVersionMatch.Success -or -not $releaseVersionMatch.Success){
  throw 'EA release version marker missing'
}
if($eaVersionMatch.Groups[1].Value -ne $releaseVersionMatch.Groups[1].Value){
  throw ("EA release version mismatch: EA={0} API={1}" -f $eaVersionMatch.Groups[1].Value,$releaseVersionMatch.Groups[1].Value)
}
Write-Host 'AUTO balanced exit / hard-target TP / fixed-lot / no-rescue contract PASS'
