$ErrorActionPreference="Stop"
function Read-Text([string]$path){if(-not(Test-Path $path)){throw "Missing source: $path"};[System.IO.File]::ReadAllText((Resolve-Path $path))}
function Need([string]$text,[string]$needle,[string]$message){if(-not $text.Contains($needle)){throw $message}}
$account=Read-Text 'apps/web/app/account/page.tsx'
$packages=Read-Text 'apps/web/app/packages/page.tsx'
$css=Read-Text 'apps/web/app/mobile-ui.css'
Need $account 'scn-mobile-account-page' 'M6 Account mobile surface missing'
Need $account 'scn-mobile-account-hub' 'M6 Account mobile hub missing'
Need $account '/dashboard?view=account' 'M6 MT5/Slots shortcut missing'
Need $account '/packages#trial-access' 'M6 Trial shortcut missing'
Need $packages 'scn-mobile-packages-page' 'M6 Packages mobile surface missing'
Need $packages 'id="trial-access"' 'M6 Trial anchor missing'
Need $packages 'id="access-center"' 'M6 Access Center anchor missing'
Need $packages 'id="membership-history"' 'M6 Membership History anchor missing'
Need $packages 'setActiveSystem("LOCAL")' 'M6 must preserve existing Local system handler'
Need $packages 'setActiveSystem("CLOUD")' 'M6 must preserve existing Cloud system handler'
Need $packages 'requestOtp' 'M6 must preserve existing Trial OTP action'
Need $packages 'checkoutLocal' 'M6 must preserve Local checkout'
Need $packages 'checkoutCloud' 'M6 must preserve Cloud checkout'
Need $css 'SCENOVA Mobile UX Upgrade · M6' 'M6 styles missing'
Need $css '@media (max-width:767px)' 'M6 must remain mobile scoped'
Write-Host 'SCENOVA mobile UI M6 account/access contract: PASS'
