$ErrorActionPreference='Stop'
function Read-Text([string]$p){ if(!(Test-Path $p)){throw "Missing $p"}; [IO.File]::ReadAllText((Resolve-Path $p)) }
function Require([string]$t,[string]$p,[string]$label){ if(-not [regex]::IsMatch($t,$p,[Text.RegularExpressions.RegexOptions]::Singleline)){throw "Phase 4 contract missing: $label"} }
function Reject([string]$t,[string]$p,[string]$label){ if([regex]::IsMatch($t,$p,[Text.RegularExpressions.RegexOptions]::Singleline)){throw "Phase 4 contract violated: $label"} }

$schema=Read-Text 'database/019_production_hardening.sql'
$startup=Read-Text 'apps/api/src/cloud-schema.ts'
$service=Read-Text 'apps/api/src/production-hardening.service.ts'
$workerApi=Read-Text 'apps/api/src/worker.controller.ts'
$worker=Read-Text 'apps/web/public/downloads/SCENOVA-CloudWorker.ps1'
$cloud=Read-Text 'apps/api/src/cloud.controller.ts'
$security=Read-Text 'apps/api/src/security.ts'
$app=Read-Text 'apps/api/src/app.module.ts'
$page=Read-Text 'apps/web/app/admin/cloud-hardening/page.tsx'
$botApi=Read-Text 'apps/api/src/bot.controller.ts'
$eaApi=Read-Text 'apps/api/src/ea.controller.ts'
$dashboard=Read-Text 'apps/web/app/dashboard/page.tsx'
$manualControls=Read-Text 'apps/web/components/Mt5ManualActionControls.tsx'

Require $schema 'CREATE TABLE IF NOT EXISTS production_controls' 'global production controls'
Require $schema 'CREATE TABLE IF NOT EXISTS runtime_incidents' 'runtime incident ledger'
Require $schema 'cloud_recovery_attempts' 'per-instance recovery budget'
Require $schema 'scenova_clear_pre_recovery_heartbeat' 'recovery clears pre-crash EA heartbeat'
Require $schema "NEW\.cloud_recovery_state='AUTHORIZED'.*NEW\.last_seen_at=NULL" 'only post-recovery heartbeat can confirm recovery'
Require $startup 'capacity_blocked' 'startup capacity guard schema'
Require $startup 'runtime_incidents' 'startup incident schema'
Require $startup 'trg_clear_pre_recovery_heartbeat' 'startup installs recovery heartbeat gate'

Require $service 'RECOVERY_MAX_ATTEMPTS\s*=\s*3' 'bounded recovery attempts'
Require $service 'RECOVERY_WINDOW_MS\s*=\s*10 \* 60_000' 'ten-minute recovery window'
Require $service 'RECOVERY_COOLDOWN_MS\s*=\s*15 \* 60_000' 'recovery circuit cooldown'
Require $service 'STALE_GENERATION' 'generation-bound recovery authorization'
Require $service 'RUNTIME_STOP_ACTIVE' 'runtime stop blocks recovery'
Require $service 'MIGRATION_ACTIVE' 'migration blocks recovery'
Require $service 'NODE_QUARANTINED' 'quarantine blocks recovery'
Require $service 'GLOBAL_RECOVERY_PAUSED' 'global recovery pause'
Require $service 'capacity_blocked' 'capacity health blocks recovery'
Reject $service 'execution_generation\s*=\s*execution_generation\s*\+\s*1' 'recovery must not rotate generation'
Reject $service 'randomBytes' 'recovery must not mint a new execution token'

Require $workerApi '@Post\("recovery-check"\)' 'worker asks server before recovery'
Require $workerApi '@Post\("recovery-result"\)' 'worker reports recovery result'
Require $workerApi 'cloud_provisioning_paused' 'claim-next obeys global provisioning pause'
Require $workerApi 'node\.quarantined \|\| node\.capacity_blocked' 'claim-next obeys automatic guard'

Require $security 'Cloud Worker v1\.2\.0\+ required for provisioning and recovery' 'old Worker fails closed for provisioning/recovery'
Require $security '"/assigned".*"/claim-next".*"/recovery-check".*"/recovery-result"' 'hardening protocol gates assigned claim and recovery routes'
Require $security 'versionAtLeast\(node\?\.telemetry\?\.version, "1\.2\.0"\)' 'hardening protocol requires Worker 1.2.0+'

Require $worker "version='1\.2\.0'" 'worker protocol version 1.2.0'
Require $worker 'diskFreeGb' 'disk free telemetry'
Require $worker "Invoke-Worker 'recovery-check'" 'worker recovery authorization call'
Require $worker 'Get-ExactTerminalProcesses \$terminal' 'exact-path duplicate check'
Require $worker 'Report-RecoveryResult \$Job ''STARTED''' 'worker recovery success report'
Require $worker 'Report-RecoveryResult \$Job ''FAILED''' 'worker recovery failure report'
Require $worker 'if \(\(Get-ExactTerminalProcesses \$terminal\)\.Count -eq 0\)' 'last duplicate check before spawn'

Require $cloud '!n\.capacity_blocked && !n\.quarantined' 'catalog excludes blocked nodes'
Require $cloud 'cloud_provisioning_paused' 'checkout obeys global provisioning pause'
Require $cloud 'NOT w\.capacity_blocked AND NOT w\.quarantined' 'allocator excludes blocked nodes'
Require $cloud 'node\.capacity_blocked \|\| node\.quarantined' 'owner cannot reopen blocked node'

Require $app 'ProductionHardeningController' 'hardening controller registered'
Require $app 'ProductionHardeningService' 'hardening service registered'
Require $page 'Pause Provisioning \+ Recovery' 'owner emergency pause UI'
Require $page 'Quarantine' 'owner quarantine UI'
Require $page 'Reset circuit' 'owner recovery circuit reset UI'

Require $botApi 'Safe Stop/Force Flat กำลังทำงานอยู่.*Position และ Pending Order ของ SCENOVA เป็น 0.*STOPPED' 'Start is blocked while Safe Stop or Force Flat drain is active'
Require $eaApi 'safeStopDrainComplete' 'Safe Stop drain has an explicit completion transition'
Require $eaApi 'heartbeatExecutionStatus === "".*heartbeatState === "SAFE_STOP".*heartbeatState === "STOPPED"' 'flat heartbeat state can finish Safe Stop when executionStatus is absent'
Require $botApi '\(livePositions > 0 \|\| livePendingOrders > 0\).*desired_state.*SAFE_STOP.*actual_state.*SAFE_STOP' 'Start blocks active SCENOVA position/pending drain, not a flat stale Safe Stop'
Require $dashboard 'safeStopPositionCount > 0.*safeStopInProgress' 'dashboard only blocks Start while positions are draining'
Require $eaApi "desired_state='STOPPED'.*desired_state='SAFE_STOP'" 'flat Safe Stop canonicalizes Server desired state to STOPPED'
Require $dashboard 'safeStopInProgress' 'dashboard blocks Start while Safe Stop is draining'
Require $dashboard 'cc-v19-hero-quick-actions.*ล้าง / ปิดทั้งหมด.*\/bot\/close-all' 'customer Force Flat Reset stays in the original top quick-action row'
Reject $dashboard 'disabled=\{busy\|\|currentPositions===0\}.*\/bot\/close-all' 'customer Force Flat Reset must remain available when cached positions are zero'
Reject $dashboard 'กำลังยืนยันการหยุดกับ EA' 'dashboard must not keep a flat Safe Stop acknowledgement banner'
Require $botApi 'const delayed = startAgeSeconds >= 20' 'slow START acknowledgement is diagnostic only'
Reject $botApi "desired_state='STOPPED',lock_owner=NULL WHERE id=\$1 AND desired_state='RUNNING' AND actual_state<>'RUNNING'" 'dashboard must never cancel a user START because acknowledgement is slow'
Require $botApi 'Server จะคง RUNNING ไว้จนกว่าจะรับคำสั่งหรือผู้ใช้กดหยุด' 'START remains user-authoritative until EA acknowledgement or explicit Stop'
Reject $manualControls 'START_COMMAND_TIMEOUT_MS' 'browser must not own a START timeout that can cancel the user request'
Reject $manualControls '/bot/stop\?slotId=' 'manual controls must never auto Safe Stop a pending START'
Require $manualControls 'data\?\.startTransition' 'manual controls use the canonical Server START transition instead of stale command logs'
Require $botApi 'dashboardPositions' 'dashboard has flat Safe Stop recovery fallback'
Require $botApi "desired_state='STOPPED',lock_owner=NULL" 'dashboard canonicalizes a flat stale Safe Stop to STOPPED'

Write-Host 'SCENOVA Phase 4 production hardening contract PASS'
