$ErrorActionPreference = 'Stop'
function Read-Text([string]$path) {
  if (-not (Test-Path $path)) { throw "Missing contract source: $path" }
  return [System.IO.File]::ReadAllText((Resolve-Path $path))
}
function Assert-Contains([string]$text,[string]$needle,[string]$label) {
  if (-not $text.Contains($needle)) { throw "ZERO runtime contract missing: $label" }
}
$mq5 = Read-Text 'mt5/FastBasketBot.mq5'
$apiRelease = Read-Text 'apps/api/src/release-version.ts'
$bot = Read-Text 'apps/api/src/bot.controller.ts'
$web = Read-Text 'apps/web/app/dashboard/page.tsx'
Assert-Contains $mq5 '#define ZERO_GRID_MAX_LEVELS 30' 'EA max 30 per side'
Assert-Contains $mq5 'JsonNumber(json, "zeroGridLevelsPerSide", g_zeroGridLevelsPerSide)' 'EA consumes saved per-side levels'
Assert-Contains $mq5 'ZERO_SIMPLE_STABLE_V117' 'EA uses simple stable ZERO runtime'
Assert-Contains $mq5 'for(int level=1;level<=levels;level++)' 'EA stages every configured ZERO level'
Assert-Contains $mq5 'if(MathAbs(requested-0.5)<0.000001) return 0.5;' 'ZERO supports 0.50 grid spacing'
Assert-Contains $mq5 'if(MathAbs(requested-1.0)<0.000001) return 1.0;' 'ZERO supports 1.00 grid spacing'
Assert-Contains $mq5 'if(MathAbs(requested-2.0)<0.000001) return 2.0;' 'ZERO supports 2.00 grid spacing'
if ($mq5.Contains('InpZeroGridLowVolatilityEnabled')) { throw 'Removed ZERO low-volatility input must not return' }
Assert-Contains $mq5 'OrderSendAsync(request,result)' 'ZERO live pending placement uses async dispatch'
Assert-Contains $mq5 'ZeroGridPendingRequestInFlight(bool buySide,int level)' 'ZERO async pending placement has duplicate in-flight guard'
Assert-Contains $mq5 '#define ZERO_GRID_PENDING_REQUEST_GUARD_MS 10000' 'ZERO async duplicate suppression window'
Assert-Contains $mq5 '#define ZERO_GRID_FLAT_CONFIRM_MS 1500' 'ZERO stable-flat rearm confirmation window'
Assert-Contains $mq5 'bool ZeroGridFlatConfirmedForReset()' 'ZERO stable-flat reset guard'
Assert-Contains $mq5 'ZERO_GRID_EXISTING_CYCLE_GUARD' 'ZERO refuses overlapping cycle when prior owned exposure exists'
Assert-Contains $mq5 '#define ZERO_GRID_DEFAULT_BASE_LOT 0.03' 'ZERO base lot defaults to 0.03'
Assert-Contains $mq5 'ZeroGridEffectiveLevelLot(int level)' 'ZERO level-lot helper exists'
Assert-Contains $mq5 'ZeroGridAllowedBaseLot(double requested)' 'EA validates ZERO base lot options'
Assert-Contains $mq5 'g_zeroGridCycleBaseLot=ZeroGridAllowedBaseLot(g_zeroGridBaseLot);' 'new ZERO cycle snapshots selected base lot'
Assert-Contains $mq5 '\"zeroGridConfiguredBaseLot\":%.2f' 'heartbeat publishes configured ZERO base lot'
Assert-Contains $bot 'metrics.zeroGridConfiguredBaseLot' 'Start guard verifies applied ZERO base lot'
Assert-Contains $web 'props.metrics?.zeroGridConfiguredBaseLot' 'UI sync verifies applied ZERO base lot'
Assert-Contains $web 'zeroGridStepPrice: 3' 'web ZERO grid step defaults to 3.00'
Assert-Contains $web 'zeroGridBaseLot: 0.03' 'web ZERO base lot defaults to 0.03'
Assert-Contains $web 'ZERO_GRID_BASE_LOT_OPTIONS = [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09]' 'web ZERO base lot selector exposes 0.01 through 0.09'
Assert-Contains $bot '[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09].includes(zeroGridBaseLot)' 'API validates allowed ZERO base lots'
Assert-Contains $web '<option value="0.5">0.50</option>' 'web ZERO grid step includes 0.50'
Assert-Contains $web '<option value="1">1.00</option>' 'web ZERO grid step includes 1.00'
if ($web.Contains('กริดตลาดความผันผวนต่ำ') -or $web.Contains('const zeroGridLowVolatilityEnabled')) { throw 'Removed ZERO low-volatility control must not return' }
if ($bot.Contains('zeroGridLowVolatilityEnabled')) { throw 'Removed ZERO low-volatility API setting must not return' }
Assert-Contains $mq5 '#define SCENOVA_RUNTIME_CONTRACT "RACE_CONFIGURED_LOSS_ONLY_V1"' 'EA loaded-runtime contract'
Assert-Contains $mq5 '\"runtimeContract\":\"%s\"' 'heartbeat runtime contract telemetry'
Assert-Contains $mq5 '\"zeroGridConfiguredLevelsPerSide\":%d' 'heartbeat configured ZERO levels telemetry'
Assert-Contains $mq5 '\"zeroGridEffectiveLevelsPerSide\":%d' 'heartbeat effective ZERO levels telemetry'
Assert-Contains $mq5 '\"zeroGridMaxLevelsPerSide\":%d' 'heartbeat max ZERO levels telemetry'
Assert-Contains $apiRelease 'EA_RUNTIME_CONTRACT = "RACE_CONFIGURED_LOSS_ONLY_V1"' 'API required runtime contract'
Assert-Contains $apiRelease 'ZERO_GRID_MAX_LEVELS_PER_SIDE = 30' 'API ZERO max 30'
Assert-Contains $bot 'runtimeContractMatch = currentRuntimeContract === requiredRuntimeContract' 'API loaded-runtime verification'
Assert-Contains $bot 'appliedLevels !== requestedLevels' 'ZERO saved-vs-applied start guard'
Assert-Contains $bot 'appliedMode !== "ZERO_GRID"' 'ZERO mode applied guard'
Assert-Contains $web 'const zeroGridSettingsSynced =' 'ZERO UI keeps applied-sync state without helper copy'
Assert-Contains $web 'Array.from({length:30},(_,i)=>i+1)' 'ZERO UI must preserve 1-30 per-side selector range'
Assert-Contains $web 'Array.from({length:30},(_,i)=>i+1)' 'ZERO UI options begin at 1'
Assert-Contains $web 'zeroGridLevelsPerSide: 10' 'ZERO UI default remains 10'
Assert-Contains $web 'EA ใน MT5 ยังไม่ได้โหลด Runtime ล่าสุด' 'loaded-runtime update alert'
Write-Host 'ZERO GRID loaded-runtime contract PASS.'
