$ErrorActionPreference = 'Stop'
function Read-Text([string]$path) {
  if (-not (Test-Path $path)) { throw "Missing contract source: $path" }
  return [System.IO.File]::ReadAllText((Resolve-Path $path))
}
function Assert-Contains([string]$text,[string]$needle,[string]$label) {
  if (-not $text.Contains($needle)) { throw "ZERO runtime contract missing: $label" }
}
$mq5 = Read-Text 'mt5/FastBasketBot.mq5'
$apiRelease = Read-Text 'apps/api/src/release-version.ts'
$bot = Read-Text 'apps/api/src/bot.controller.ts'
$web = Read-Text 'apps/web/app/dashboard/page.tsx'
Assert-Contains $mq5 '#define ZERO_GRID_MAX_LEVELS 30' 'EA max 30 per side'
Assert-Contains $mq5 'JsonNumber(json, "zeroGridLevelsPerSide", g_zeroGridLevelsPerSide)' 'EA consumes saved per-side levels'
Assert-Contains $mq5 'ZERO_SIMPLE_STABLE_V117' 'EA uses simple stable ZERO runtime'
Assert-Contains $mq5 'for(int level=1;level<=levels;level++)' 'EA stages every configured ZERO level'
Assert-Contains $mq5 'InpZeroGridLowVolatilityEnabled = false;' 'low-volatility mode defaults OFF in EA'
Assert-Contains $mq5 'JsonBool(json, "zeroGridLowVolatilityEnabled"' 'EA consumes the low-volatility switch'
Assert-Contains $mq5 'ZeroGridEffectiveLowVolatilityEnabled() ? 0.10 : 3.0' 'normal first pending gap is 3.00; low-volatility stays 0.10'
Assert-Contains $mq5 'g_zeroGridLowVolatilityEnabled ? 0.30' 'low-volatility fixed grid spacing'
Assert-Contains $mq5 'OrderSendAsync(request,result)' 'ZERO live pending placement uses async dispatch'
Assert-Contains $mq5 'ZeroGridPendingRequestInFlight(bool buySide,int level)' 'ZERO async pending placement has duplicate in-flight guard'
Assert-Contains $mq5 '#define ZERO_GRID_PENDING_REQUEST_GUARD_MS 10000' 'ZERO async duplicate suppression window'
Assert-Contains $mq5 '#define ZERO_GRID_FLAT_CONFIRM_MS 1500' 'ZERO stable-flat rearm confirmation window'
Assert-Contains $mq5 'bool ZeroGridFlatConfirmedForReset()' 'ZERO stable-flat reset guard'
Assert-Contains $mq5 'ZERO_GRID_EXISTING_CYCLE_GUARD' 'ZERO refuses overlapping cycle when prior owned exposure exists'
Assert-Contains $mq5 '#define ZERO_GRID_LOCKED_BASE_LOT 0.03' 'ZERO base lot is locked at 0.03'
Assert-Contains $mq5 'ZeroGridEffectiveLevelLot(int level)' 'ZERO level-lot helper exists'
Assert-Contains $web 'zeroGridLowVolatilityEnabled: false' 'web low-volatility mode defaults OFF'
Assert-Contains $web 'zeroGridBaseLot: 0.03' 'web ZERO base lot defaults to locked 0.03'
Assert-Contains $web '<b>0.03 Lot</b>' 'web ZERO base lot control is read-only at 0.03'
Assert-Contains $bot 'clean.zeroGridBaseLot = 0.03;' 'API persists locked ZERO base lot'
Assert-Contains $web 'กริดตลาดความผันผวนต่ำ' 'professional low-volatility UI card'
Assert-Contains $bot 'booleanSetting("zeroGridLowVolatilityEnabled")' 'API validates low-volatility switch'
Assert-Contains $mq5 '#define SCENOVA_RUNTIME_CONTRACT "RACE_CONFIGURED_LOSS_ONLY_V1"' 'EA loaded-runtime contract'
Assert-Contains $mq5 '\"runtimeContract\":\"%s\"' 'heartbeat runtime contract telemetry'
Assert-Contains $mq5 '\"zeroGridConfiguredLevelsPerSide\":%d' 'heartbeat configured ZERO levels telemetry'
Assert-Contains $mq5 '\"zeroGridEffectiveLevelsPerSide\":%d' 'heartbeat effective ZERO levels telemetry'
Assert-Contains $mq5 '\"zeroGridMaxLevelsPerSide\":%d' 'heartbeat max ZERO levels telemetry'
Assert-Contains $apiRelease 'EA_RUNTIME_CONTRACT = "RACE_CONFIGURED_LOSS_ONLY_V1"' 'API required runtime contract'
Assert-Contains $apiRelease 'ZERO_GRID_MAX_LEVELS_PER_SIDE = 30' 'API ZERO max 30'
Assert-Contains $bot 'runtimeContractMatch = currentRuntimeContract === requiredRuntimeContract' 'API loaded-runtime verification'
Assert-Contains $bot 'appliedLevels !== requestedLevels' 'ZERO saved-vs-applied start guard'
Assert-Contains $bot 'appliedMode !== "ZERO_GRID"' 'ZERO mode applied guard'
Assert-Contains $web 'const zeroGridSettingsSynced =' 'ZERO UI keeps applied-sync state without helper copy'
Assert-Contains $web 'Array.from({length:30},(_,i)=>i+1)' 'ZERO UI must preserve 1-30 per-side selector range'
Assert-Contains $web 'Array.from({length:30},(_,i)=>i+1)' 'ZERO UI options begin at 1'
Assert-Contains $web 'zeroGridLevelsPerSide: 10' 'ZERO UI default remains 10'
Assert-Contains $web 'EA ใน MT5 ยังไม่ได้โหลด Runtime ล่าสุด' 'loaded-runtime update alert'
Write-Host 'ZERO GRID loaded-runtime contract PASS.'
