export const SCENOVA_BRAND_NAME = "SCENOVA EA";
export const SCENOVA_MASTER_MARK = "/brand/scenova-master-1254.png";
export const SCENOVA_MASTER_LOGO = SCENOVA_MASTER_MARK;
export const SCENOVA_APPLE_TOUCH_ICON = SCENOVA_MASTER_MARK;
