"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { api, getToken } from "../../lib/api";
import { Badge, CloudPackage, date, money } from "../../components/CloudConsole";
import s from "../../components/cloud.module.css";

type Catalog={packages:CloudPackage[];available:number;paymentMode:string;checkoutEnabled:boolean};
type Order={id:string;months:number;amount:number;status:string;qr_url:string|null;expires_at:string|null;created_at:string;slot_id:string|null;subscription_expires_at:string|null;actual_state:string|null;last_seen_at:string|null;account_number:string|null};
export default function CloudMembershipPage(){
  const [catalog,setCatalog]=useState<Catalog|null>(null);const [orders,setOrders]=useState<Order[]>([]);
  const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [slotId,setSlotId]=useState("");
  const polling=useRef(false);
  async function load(){const [c,o]=await Promise.all([api("/cloud/catalog"),api("/cloud/orders")]);setCatalog(c);setOrders(o);}
  useEffect(()=>{if(!getToken()){window.location.href="/login";return;}setSlotId(new URLSearchParams(window.location.search).get("slotId")||"");load().catch(e=>setError(e.message));const id=setInterval(()=>{if(!document.hidden)load().catch(e=>setError(e.message));},10000);return()=>clearInterval(id);},[]);
  const pending=orders.find(o=>["CREATING","PENDING","REVIEW"].includes(o.status));
  // Reconcile on a slower cadence as a fallback when a webhook is delayed.
  useEffect(()=>{if(!pending||pending.status!=="PENDING")return;const id=setInterval(async()=>{if(document.hidden||polling.current)return;polling.current=true;try{await api(`/cloud/orders/${pending.id}/refresh`,{method:"POST"});await load();}catch(e:any){setError(e.message);}finally{polling.current=false;}},20000);return()=>clearInterval(id);},[pending?.id,pending?.status]);
  async function refreshOrder(id:string){setBusy(true);setError("");try{await api(`/cloud/orders/${id}/refresh`,{method:"POST"});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function checkout(months:number){setBusy(true);setError("");try{await api("/cloud/checkout",{method:"POST",body:JSON.stringify({months,slotId:slotId||undefined})});await load();}catch(e:any){setError(e.message);await load().catch(()=>{});}finally{setBusy(false);}}
  const paid=orders.filter(o=>o.status==="PAID").filter((o,index,list)=>list.findIndex(v=>v.slot_id===o.slot_id)===index);
  return <main className={`${s.customer} ${s.root}`}><header className={s.customerHeader}><Link href="/dashboard" className={s.brand}>SCENOVA</Link><Link className={s.button} href="/dashboard?view=account">กลับไปบัญชีของฉัน ↗</Link></header>
    <section className={s.hero}><div><span className={s.eyebrow}>YOUR PERSONAL CLOUD MT5</span><h2>บอทอยู่บน Cloud<br/>คุณควบคุมได้ทุกที่</h2><p>ไม่ต้องเปิดคอมพิวเตอร์ส่วนตัว เลือกระยะเวลาที่เหมาะกับคุณ เชื่อมบัญชี MT5 แล้วควบคุมบอทผ่านเว็บหรือมือถือ</p><div className={s.actions}><Badge tone={catalog?.available?"good":"warn"}>{catalog?`${catalog.available} Cloud MT5 พร้อมให้บริการ`:"กำลังตรวจสอบความพร้อม"}</Badge><span className={s.muted}>1 แพ็กเกจ · 1 บัญชี MT5</span></div></div><div className={s.diagram}><span className={s.eyebrow}>GET STARTED</span><div className={s.steps}>{[["เลือกแพ็กเกจ","1 / 3 / 6 / 12 เดือน"],["สแกน QR ชำระเงิน","ยืนยันยอดและเปิดสิทธิ์อัตโนมัติ"],["เชื่อม MT5 แล้วกด Start","เริ่มได้เมื่อ EA บน Cloud ออนไลน์"]].map(([title,body],i)=><div key={title} className={s.step}><span className={s.stepNumber}>{i+1}</span><div><b>{title}</b><p>{body}</p></div></div>)}</div></div></section>
    {error&&<div role="alert" className={`${s.notice} ${s.error}`}>{error}</div>}
    {catalog?.paymentMode==="TEST"&&<div className={s.notice}>โหมดทดสอบ — QR และสิทธิ์จากรายการนี้ใช้ทดสอบระบบ ยังไม่ใช่การรับชำระเงินจริง</div>}
    {catalog&&!catalog.checkoutEnabled&&<div className={s.notice}>กำลังเตรียมเปิดบริการ Cloud ขณะนี้ยังไม่รับชำระเงิน</div>}
    {pending&&<section className={s.panel} aria-live="polite"><div className={s.panelHead}><div><span className={s.eyebrow}>YOUR ORDER / {pending.id.slice(0,8)}</span><h3>{pending.status==="REVIEW"?"กำลังตรวจสอบรายการ":"สแกน QR เพื่อเปิดใช้งาน"}</h3></div><Badge tone="warn">{pending.status}</Badge></div><div className={`${s.panelBody} ${s.checkout}`}><div>{pending.qr_url&&/^https:\/\//.test(pending.qr_url)&&pending.status==="PENDING"?<img className={s.qr} src={pending.qr_url} alt={`QR PromptPay ชำระแพ็กเกจ Cloud ${pending.months} เดือน จำนวน ${money(pending.amount)} บาท`} referrerPolicy="no-referrer"/>:<p className={s.muted}>กรุณาติดต่อผู้ดูแลพร้อมเลขรายการ {pending.id} หากรายการยังไม่เปลี่ยนสถานะ</p>}</div><div><span className={s.eyebrow}>CLOUD {pending.months} MONTHS</span><h3 className={s.price}>฿{money(pending.amount)}</h3><p className={s.muted}>สแกนผ่านแอปธนาคาร หรือบันทึกภาพ QR เพื่อเลือกจากแกลเลอรีในแอปธนาคาร<br/>QR หมดอายุ: {pending.expires_at?date(pending.expires_at):"รอผู้ให้บริการยืนยัน"}</p><p className={s.muted}>ระบบจะอัปเดตเมื่อธนาคารยืนยันยอด ไม่ต้องส่งสลิป หากชำระแล้วอย่าสร้างรายการใหม่</p><button className={`${s.button} ${s.primary}`} disabled={busy} onClick={()=>refreshOrder(pending.id)}>{busy?"กำลังตรวจสอบ…":"ตรวจสอบการชำระเงิน"}</button></div></div></section>}
    {paid.length>0&&<section className={s.panel}><div className={s.panelHead}><div><span className={s.eyebrow}>MY CLOUD</span><h3>พื้นที่ Cloud ของคุณ</h3></div></div><div className={s.panelBody}><div className={s.nodes}>{paid.map(o=>{const online=!!o.last_seen_at&&Date.now()-new Date(o.last_seen_at).getTime()<30000;const active=!!o.subscription_expires_at&&new Date(o.subscription_expires_at).getTime()>Date.now();return <article className={s.nodeCard} key={o.id}><div className={s.nodeHead}><h3>{o.account_number?`MT5 ${o.account_number}`:"เชื่อมบัญชี MT5 ของคุณ"}</h3><Badge tone={active?"good":"warn"}>{active?"เปิดสิทธิ์แล้ว":"หมดอายุ"}</Badge></div><p className={s.muted}>ใช้ได้ถึง {date(o.subscription_expires_at)}<br/>{!o.account_number?"ขั้นตอนถัดไป: เชื่อมบัญชีและ Trading Password":online?`EA ออนไลน์ · ${o.actual_state}`:"กำลังเตรียม MT5 / รอ EA เชื่อมต่อ"}</p><div className={s.actions}><Link className={`${s.button} ${s.primary}`} href={`/dashboard?view=${online?"overview":"account"}&slotId=${o.slot_id}`}>{online?"ไปที่ Control Center":"ตั้งค่า MT5"} →</Link><button className={s.button} onClick={()=>{setSlotId(o.slot_id||"");document.getElementById("cloud-packages")?.scrollIntoView({behavior:"smooth"});}}>ต่ออายุ</button></div></article>;})}</div></div></section>}
    <div id="cloud-packages" className={s.topline}><div><span className={s.eyebrow}>FLEXIBLE MEMBERSHIP</span><h2>{slotId?"ต่ออายุ Cloud":"เลือกแพ็กเกจของคุณ"}</h2></div>{slotId&&<button className={s.button} onClick={()=>setSlotId("")}>ซื้อ Cloud เพิ่ม</button>}</div>
    <div className={s.packages}>{(catalog?.packages||[]).map(p=><article className={`${s.package} ${p.months===3?s.featured:""}`} key={p.months}><span className={s.eyebrow}>CLOUD MT5</span><h3>{p.months} เดือน</h3><div className={s.price}>{p.price_satang>0?`฿${money(p.price_satang)}`:"รอประกาศราคา"}<small>{p.price_satang>0?`เฉลี่ย ฿${money(Math.round(p.price_satang/p.months))} / เดือน`:"ราคาจะแสดงเมื่อพร้อมเปิดขาย"}</small></div><div className={s.features}><span>Cloud สำหรับ 1 บัญชี MT5</span><span>Start / Stop ผ่านมือถือ</span><span>ดูสถานะบอทได้ตลอด</span><span>ต่ออายุรักษาเวลาที่เหลือ</span></div><button className={`${s.button} ${p.months===3?s.primary:""}`} disabled={busy||!!pending||!catalog?.checkoutEnabled||!p.enabled||p.price_satang<=0||(!slotId&&!catalog?.available)} onClick={()=>checkout(p.months)}>{busy?"กำลังดำเนินการ…":!p.enabled?"ยังไม่เปิดขาย":slotId?"ต่ออายุด้วย QR":"เลือกแพ็กเกจ"}</button><small className={s.muted}>ชำระครั้งเดียว ไม่ตัดเงินต่ออายุอัตโนมัติ</small></article>)}</div>
    {!catalog&&!error&&<div className={s.spinner}>กำลังโหลดแพ็กเกจ…</div>}
    <section className={s.panel}><div className={s.panelHead}><h3>ประวัติคำสั่งซื้อ</h3></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>รายการ</th><th>แพ็กเกจ</th><th>ยอดชำระ</th><th>สถานะ</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td title={o.id}>{o.id.slice(0,8)}<small>{date(o.created_at)}</small></td><td>{o.months} เดือน</td><td>฿{money(o.amount)}</td><td><Badge tone={o.status==="PAID"?"good":o.status==="FAILED"?"bad":"warn"}>{o.status==="PAID"?"ชำระแล้ว":o.status==="FAILED"?"ไม่สำเร็จ":o.status==="REVIEW"?"กำลังตรวจสอบ":"รอชำระ"}</Badge></td></tr>)}</tbody></table></div>{!orders.length&&<p className={`${s.panelBody} ${s.muted}`}>ยังไม่มีคำสั่งซื้อ</p>}</section>
    <p className={s.muted}>ระยะสมาชิกเริ่มเมื่อยืนยันการชำระเงินสำเร็จ หากต่ออายุก่อนหมดจะเพิ่มจากเวลาคงเหลือเดิม เมื่อหมดอายุ EA จะไม่เปิดรอบใหม่และเข้าสู่ Safe Stop การเปิดสิทธิ์ไม่เริ่มเทรดเอง</p>
  </main>;
}
