"use client";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import Link from "next/link";
import { adminApi } from "../lib/api";
import { useSystemPopup } from "./SystemPopupProvider";
import s from "./cloud.module.css";

export type CloudPackage = { months:number; price_satang:number; enabled:boolean; updated_at:string };
type Node = { runner_id:string; region:string; hostname:string; capacity:number; occupied:number; active_instances:number; accepting_jobs:boolean; health:string; monthly_cost:number; spec:string; last_seen_at:string|null; telemetry:{ cpuPercent?:number|null; ramUsedGb?:number|null; ramTotalGb?:number|null; templateReady?:boolean } };
type Snapshot = { packages:CloudPackage[]; localPackages:CloudPackage[]; nodes:Node[]; orders:any[]; instances:any[]; available:number; checkoutEnabled:boolean; paymentMode:string };
type Tab = "overview"|"nodes"|"packages"|"orders"|"setup";
export const money = (satang:number) => new Intl.NumberFormat("th-TH", { maximumFractionDigits:2 }).format(satang/100);
export const date = (value:string|null|undefined) => value ? new Date(value).toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"short"}) : "ยังไม่เชื่อมต่อ";
export function Badge({children,tone=""}:{children:ReactNode;tone?:string}) { return <span className={`${s.badge} ${tone==="good"?s.good:tone==="warn"?s.warn:tone==="bad"?s.bad: ""}`}>{children}</span>; }
function Panel({title,kicker,action,children}:{title:string;kicker?:string;action?:ReactNode;children:ReactNode}) { return <section className={s.panel}><div className={s.panelHead}><div>{kicker&&<span className={s.eyebrow}>{kicker}</span>}<h3>{title}</h3></div>{action}</div>{children}</section>; }
function Empty({title,body,action}:{title:string;body:string;action?:ReactNode}) { return <div className={s.empty}><span className={s.emptyIcon}>☁</span><b>{title}</b><p>{body}</p>{action}</div>; }
export function CloudConsole() {
  const { confirmPopup } = useSystemPopup();
  const [data,setData]=useState<Snapshot|null>(null);
  const [tab,setTab]=useState<Tab>("overview");
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [busy,setBusy]=useState(false);
  const [showAdd,setShowAdd]=useState(false);
  const [credential,setCredential]=useState<{runnerId:string;workerKey:string}|null>(null);
  const [serverEnrollment,setServerEnrollment]=useState<{runnerId:string;enrollmentToken:string;expiresAt:string}|null>(null);
  const [updated,setUpdated]=useState("");
  async function load() { try { const [cloud,localPackages]=await Promise.all([adminApi("/admin/cloud"),adminApi("/admin/local-packages")]);setData({...cloud,localPackages});setUpdated(new Date().toLocaleTimeString("th-TH")); } catch(e:any) {setError(e.message);} }
  useEffect(()=>{load();const timer=setInterval(()=>{if(!document.hidden)load();},15000);return()=>clearInterval(timer);},[]);
  async function save(path:string,body:any) { setBusy(true);setError("");setNotice("");try { const result=await adminApi("/admin/cloud"+path,{method:"POST",body:JSON.stringify(body)});await load();setNotice("บันทึกข้อมูลเรียบร้อย");return result; } catch(e:any){setError(e.message);return null;} finally{setBusy(false);} }
  async function saveLocalPackage(body:any) { setBusy(true);setError("");setNotice("");try { const result=await adminApi("/admin/local-packages",{method:"POST",body:JSON.stringify(body)});await load();setNotice("บันทึกแพ็กเกจ Local เรียบร้อย");return result; } catch(e:any){setError(e.message);return null;} finally{setBusy(false);} }
  async function add(e:FormEvent<HTMLFormElement>) { e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError("");setNotice("");try{const result=await adminApi("/admin/cloud-servers",{method:"POST",body:JSON.stringify({runnerId:form.get("runnerId"),region:form.get("region"),capacity:Number(form.get("capacity")),monthlyCost:Number(form.get("cost")),spec:form.get("spec")})});await load();setServerEnrollment(result);setShowAdd(false);setTab("setup");setNotice("สร้าง Server และรหัสติดตั้งชั่วคราวแล้ว");}catch(e:any){setError(e.message);}finally{setBusy(false);} }
  if(!data) return <div className={s.root}>{error?<div role="alert" className={`${s.notice} ${s.error}`}>{error}<button className={s.button} onClick={load}>ลองอีกครั้ง</button></div>:<div className={s.spinner}>กำลังเชื่อม Cloud Console…</div>}</div>;
  const online=data.nodes.filter(n=>n.health==="ONLINE").length;
  const occupied=data.nodes.reduce((sum,n)=>sum+Math.max(n.occupied,n.active_instances),0);
  const total=data.nodes.reduce((sum,n)=>sum+n.capacity,0);
  const cost=data.nodes.reduce((sum,n)=>sum+n.monthly_cost,0);
  const ready=data.checkoutEnabled&&data.paymentMode==="LIVE"&&data.available>0&&data.packages.some(p=>p.enabled&&p.price_satang>0);
  const nav: [Tab,string][]=[["overview","ภาพรวม"],["nodes","VPS & MT5"],["packages","แพ็กเกจ"],["orders","คำสั่งซื้อ"],["setup","ตั้งค่าการเชื่อมต่อ"]];
  const openAdd=()=>{setTab("nodes");setShowAdd(true);};
  const setupSteps=[{title:"เชื่อม Windows VPS",body:"เพิ่มเครื่อง ติดตั้ง Worker และตรวจ MT5 Template",done:data.nodes.some(n=>n.health==="ONLINE"&&n.telemetry?.templateReady)},
    {title:"ตั้งราคาแพ็กเกจ",body:"กำหนดราคา 1 / 3 / 6 / 12 เดือน แล้วเลือกเปิดขาย",done:data.packages.some(p=>p.enabled&&p.price_satang>0)},
    {title:"เชื่อม PromptPay",body:"ตั้งค่า Opn/Omise และ Webhook ยืนยันการชำระเงิน",done:data.paymentMode==="LIVE"},
    {title:"เปิดรับลูกค้า",body:"ทดสอบครบวงจร เปิด Checkout และเปิดรับงานบน VPS",done:ready}];
  return <div className={s.root}>
    <section className={s.hero}><div><span className={s.eyebrow}>SCENOVA CLOUD / INFRASTRUCTURE</span><h2>พื้นที่พร้อมเทรด<br/>สำหรับลูกค้าของคุณ</h2><p>จัดการ VPS แพ็กเกจ และการเปิดใช้งานจากที่เดียว<br/>รองรับหลายเซิร์ฟเวอร์ พร้อมจัดสรร MT5 ให้แต่ละบัญชี</p><div className={s.actions}><button className={`${s.button} ${s.primary}`} onClick={openAdd}>＋ เพิ่ม VPS</button><Link className={s.button} href="/packages">ดูหน้า Packages ↗</Link></div></div>
      <div className={s.diagram}><div className={s.diagramTop}><div><span className={s.eyebrow}>CONTROL PLANE</span><h3 style={{margin:"8px 0"}}>SCENOVA Cloud</h3><small>เว็บเดียว · หลาย Trading Nodes</small></div><Badge tone={ready?"good":"warn"}>{ready?"พร้อมเปิดขาย":"กำลังเตรียมระบบ"}</Badge></div><div className={s.nodeGrid}>{data.nodes.length?data.nodes.slice(0,4).map(n=><div className={s.miniNode} key={n.runner_id}><b>▤ {n.runner_id}</b><Badge tone={n.health==="ONLINE"?"good":""}>{n.health}</Badge><small>{Math.max(n.occupied,n.active_instances)} / {n.capacity} MT5</small></div>):<><div className={s.miniNode}><b>▤ VPS ตัวแรก</b><small>รอการเชื่อมต่อ</small></div><div className={s.miniNode}><b>＋ ขยายเมื่อพร้อม</b><small>เพิ่มเครื่องได้ภายหลัง</small></div></>}</div></div>
    </section>
    <div className={s.stats}>{[["VPS ออนไลน์",`${online} / ${data.nodes.length}`,"เครื่องที่ติดต่อใน 30 วินาทีล่าสุด"],["MT5 ใช้ / จอง",`${occupied} / ${total}`,"รวมรายการชำระเงินที่กำลังตรวจสอบ"],["พร้อมรับลูกค้า",String(data.available),"บัญชี Cloud บนเครื่องออนไลน์ที่เปิดรับงาน"],["ต้นทุน VPS / เดือน",`฿${money(cost*100)}`,"ตามต้นทุนเครื่องที่คุณระบุ"]].map(([label,value,hint])=><div key={label} className={s.stat}><div className={s.statLabel}>{label}<span>↗</span></div><strong>{value}</strong><small>{hint}</small></div>)}</div>
    <div className={s.topline}><nav className={s.tabs} aria-label="Cloud sections">{nav.map(([id,label])=><button key={id} className={`${s.tab} ${tab===id?s.tabActive:""}`} aria-current={tab===id?"page":undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav><button className={s.button} onClick={load} disabled={busy} aria-label="รีเฟรช Cloud">↻</button></div>
    {error&&<div role="alert" className={`${s.notice} ${s.error}`}>{error}</div>}{notice&&<div role="status" className={`${s.notice} ${s.success}`}>{notice}</div>}
    {tab==="overview"&&<div className={s.split}><Panel title="Trading fleet" kicker="YOUR INFRASTRUCTURE" action={<button className={s.button} onClick={()=>setTab("nodes")}>จัดการ VPS →</button>}>{data.nodes.length?<div className={s.tableWrap}><table className={s.table}><thead><tr><th>SERVER</th><th>CAPACITY</th><th>STATUS</th></tr></thead><tbody>{data.nodes.map(n=><tr key={n.runner_id}><td><b>{n.runner_id}</b><small>{n.region}</small></td><td>{Math.max(n.occupied,n.active_instances)} / {n.capacity}<div className={s.bar}><span style={{width:Math.min(100,Math.max(n.occupied,n.active_instances)/n.capacity*100)+"%"}}/></div></td><td><Badge tone={n.health==="ONLINE"?"good":"warn"}>{n.health==="ONLINE"?n.accepting_jobs?"รับลูกค้าใหม่":"พักรับลูกค้า":"รอเชื่อมต่อ"}</Badge></td></tr>)}</tbody></table></div>:<Empty title="เริ่มต้นด้วย VPS ตัวแรก" body="เพิ่มเครื่องของคุณและติดตั้ง Cloud Worker รายการนี้จะแสดงสถานะจริงเมื่อเครื่องเชื่อมต่อสำเร็จ" action={<button className={`${s.button} ${s.primary}`} onClick={openAdd}>＋ เพิ่ม VPS ตัวแรก</button>}/>}</Panel><Panel title="เตรียมเปิดบริการ" kicker={`${setupSteps.filter(x=>x.done).length} / 4 STEPS`}><div className={s.panelBody}><div className={s.steps}>{setupSteps.map((step,i)=><div className={s.step} key={step.title}><span className={s.stepNumber}>{step.done?"✓":i+1}</span><div><b>{step.title}</b><p>{step.body}</p></div></div>)}</div><button className={s.button} onClick={()=>setTab("setup")}>ตั้งค่าการเชื่อมต่อ →</button></div></Panel></div>}
    {tab==="nodes"&&<>
      {showAdd&&<Panel title="เพิ่ม Windows Trading VPS" action={<button className={s.button} onClick={()=>setShowAdd(false)}>ปิด</button>}><form className={`${s.panelBody} ${s.form}`} onSubmit={add}><div className={s.formGrid}><label className={s.field}>Runner ID<input name="runnerId" required pattern="[a-zA-Z0-9_-]{3,80}" placeholder="scenova-th-01"/></label><label className={s.field}>ภูมิภาค<input name="region" required defaultValue="Thailand" maxLength={80}/></label><label className={s.field}>จำนวน MT5 สูงสุด<input name="capacity" type="number" min={1} max={200} defaultValue={2} required/></label><label className={s.field}>ค่าเช่าต่อเดือน (บาท)<input name="cost" type="number" min={0} max={1000000} defaultValue={4000} required/></label><label className={s.field}>สเปก / หมายเหตุ<input name="spec" placeholder="E5-2690 · 16 vCore · 96 GB RAM" maxLength={300}/></label></div><p className={s.muted}>เริ่ม Capacity ต่ำ แล้วเพิ่มตามผลทดสอบจริง การเพิ่มรายการนี้ยังไม่ได้เช่าหรือสร้าง VPS ให้</p><div><button disabled={busy} className={`${s.button} ${s.primary}`}>สร้าง Server และรหัสติดตั้ง</button></div></form></Panel>}
      <div className={s.nodes}>{data.nodes.map(n=><NodeCard key={n.runner_id+":"+n.capacity+":"+n.accepting_jobs} node={n} busy={busy} save={save}/>)}</div>
      {!data.nodes.length&&!showAdd&&<Panel title="Windows Trading Nodes"><Empty title="ยังไม่มี VPS" body="รองรับการแบ่งลูกค้าข้ามหลายเครื่อง แต่ละบัญชีใช้ MT5 และโฟลเดอร์ของตัวเอง" action={<button className={`${s.button} ${s.primary}`} onClick={openAdd}>＋ เพิ่ม VPS</button>}/></Panel>}
      <Panel title="Cloud MT5 ของลูกค้า" kicker="PROVISIONING & HEALTH"><div className={s.tableWrap}><table className={s.table}><thead><tr><th>ลูกค้า / บัญชี</th><th>VPS</th><th>สถานะ</th><th>ติดต่อครั้งล่าสุด</th></tr></thead><tbody>{data.instances.map(i=><tr key={i.id}><td>{i.user_code||"—"}<small>{i.account_number||"รอเชื่อม MT5"}</small></td><td>{i.runner_id||"รอจัดสรร"}</td><td><Badge tone={i.last_seen_at&&Date.now()-new Date(i.last_seen_at).getTime()<30000?"good":"warn"}>{!i.credential_ready?"รอข้อมูลบัญชี":!i.runner_id?"รอ Worker":i.last_seen_at&&Date.now()-new Date(i.last_seen_at).getTime()<30000?i.actual_state:"รอ EA ออนไลน์"}</Badge>{i.provisioning_error&&<small>{i.provisioning_error}</small>}</td><td>{date(i.last_seen_at)}</td></tr>)}</tbody></table></div>{!data.instances.length&&<Empty title="ยังไม่มี Cloud MT5" body="เมื่อเปิดสิทธิ์และลูกค้าเชื่อมบัญชีแล้ว Worker จะรับงานและเปิด MT5 ให้อัตโนมัติ"/>}</Panel>
    </>}
    {tab==="packages"&&<><div className={s.notice}>Local และ Cloud แยกระบบและราคาออกจากกัน · 1 แพ็กเกจ = 1 บัญชี MT5 · ต่ออายุจากเวลาที่เหลือเดิม</div><Panel title="Local MT5 Packages" kicker="LOCAL SYSTEM"><div className={s.panelBody}><div className={s.packages}>{data.localPackages.map(p=><PackageEditor key={"local:"+p.months+":"+p.updated_at} pack={p} busy={busy} system="LOCAL" save={async(_path,body)=>saveLocalPackage(body)}/>)}</div><p className={s.muted}>Local ใช้ MT5 บนเครื่องลูกค้าเอง เปิดขายได้เมื่อกำหนดราคาและเปิด LOCAL_CHECKOUT_ENABLED</p></div></Panel><Panel title="Cloud MT5 Packages" kicker="CLOUD SYSTEM"><div className={s.panelBody}><div className={s.packages}>{data.packages.map(p=><PackageEditor key={"cloud:"+p.months+":"+p.updated_at} pack={p} busy={busy} system="CLOUD" save={save}/>)}</div><p className={s.muted}>Cloud เปิดขายได้เมื่อกำหนดราคา เปิด Checkout และมี VPS Capacity พร้อมใช้งาน</p></div></Panel></>}
    {tab==="orders"&&<Panel title="คำสั่งซื้อ Cloud" kicker="PAYMENTS & ACTIVATION" action={<Badge tone={data.paymentMode==="LIVE"?"good":"warn"}>{data.paymentMode}</Badge>}><div className={s.tableWrap}><table className={s.table}><thead><tr><th>รายการ / ลูกค้า</th><th>แพ็กเกจ</th><th>ยอดรวม</th><th>สถานะ</th><th>VPS</th><th>ตรวจสอบ</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td title={o.id}>{o.user_code}<small>{o.id.slice(0,8)} · {date(o.created_at)}</small></td><td>{o.months} เดือน</td><td>฿{money(o.amount)}</td><td><Badge tone={o.status==="PAID"?"good":o.status==="FAILED"?"bad":"warn"}>{o.status}</Badge></td><td>{o.runner_id}</td><td>{o.charge_id&&o.status!=="PAID"?<button className={s.button} disabled={busy} onClick={()=>save("/reconcile",{chargeId:o.charge_id})}>ตรวจยอด</button>:o.status==="REVIEW"?"ตรวจที่ Gateway":"—"}</td></tr>)}</tbody></table></div>{!data.orders.length&&<Empty title="คำสั่งซื้อจะปรากฏที่นี่" body="ติดตาม QR ที่รอชำระ ยืนยันยอด และเปิดสิทธิ์อัตโนมัติจากข้อมูลผู้ให้บริการชำระเงิน"/>}</Panel>}
    {tab==="setup"&&<>
      {serverEnrollment&&<Panel title="Server Enrollment" kicker="PHASE 1 / ONE-TIME"><div className={`${s.panelBody} ${s.form}`}><p className={s.muted}>Server <b>{serverEnrollment.runnerId}</b> ถูกสร้างแล้ว รหัสนี้ใช้ได้ครั้งเดียวและหมดอายุอัตโนมัติ Phase 2 จะนำรหัสนี้ไปผูกกับตัวติดตั้ง Server โดยไม่ต้อง Login Admin บน VPS</p><code className={s.code}>{serverEnrollment.enrollmentToken}</code><p className={s.muted}>หมดอายุ {new Date(serverEnrollment.expiresAt).toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"short"})}</p><div className={s.inline}><button className={s.button} onClick={async()=>{try{await navigator.clipboard.writeText(serverEnrollment.enrollmentToken);setNotice("คัดลอกรหัสติดตั้ง Server แล้ว");}catch{setError("คัดลอกไม่สำเร็จ กรุณาคัดลอกด้วยตนเอง");}}}>คัดลอกรหัสติดตั้ง</button><button className={s.button} onClick={()=>setServerEnrollment(null)}>ซ่อนรหัส</button></div></div></Panel>}
      <Panel title="เปลี่ยน Worker Key" kicker="NODE ACCESS"><form className={`${s.panelBody} ${s.form}`} onSubmit={async e=>{e.preventDefault();const id=String(new FormData(e.currentTarget).get("runnerId")||"");if(!id)return;const confirmed=await confirmPopup({title:"เปลี่ยน Worker Key",tone:"warning",message:"เปลี่ยน Key ของ "+id+"? Worker เดิมจะเชื่อมต่อไม่ได้จนกว่าจะติดตั้ง Key ใหม่ และเครื่องจะพักรับลูกค้าใหม่",confirmLabel:"สร้าง Key ใหม่"});if(!confirmed)return;const result=await save("/nodes/"+encodeURIComponent(id)+"/rotate-key",{});if(result)setCredential(result);}}><div className={s.inline}><label className={s.field}>VPS<select name="runnerId" required><option value="">เลือกเครื่อง</option>{data.nodes.map(n=><option key={n.runner_id} value={n.runner_id}>{n.runner_id}</option>)}</select></label><button disabled={busy||!data.nodes.length} className={s.button}>สร้าง Key ใหม่</button></div></form></Panel>
      {credential&&<Panel title="Worker Key สำหรับเครื่องใหม่" kicker="แสดงครั้งเดียว"><div className={`${s.panelBody} ${s.form}`}><p className={s.muted}>เก็บไว้บน VPS ของคุณ ใช้ยืนยันตัวตนเฉพาะเครื่อง {credential.runnerId} แล้วกดซ่อนเมื่อบันทึกเสร็จ</p><code className={s.code}>{credential.workerKey}</code><div className={s.inline}><button className={s.button} onClick={async()=>{try{await navigator.clipboard.writeText(credential.workerKey);setNotice("คัดลอก Worker Key แล้ว");}catch{setError("คัดลอกไม่สำเร็จ กรุณาคัดลอกด้วยตนเอง");}}}>คัดลอก Key</button><button className={s.button} onClick={()=>setCredential(null)}>ซ่อน Key</button></div></div></Panel>}
      <div className={s.split}><Panel title="เชื่อม Windows VPS" kicker="01 / TRADING WORKER"><div className={`${s.panelBody} ${s.form}`}><div className={s.steps}>{[{title:"เตรียม MT5 Template",body:"ติดตั้ง MT5 ใน C:\\BotTrading\\template ใส่ FastBasketBot.ex5 ที่ MQL5\\Experts เปิด Algo Trading และอนุญาต WebRequest ของ API แล้วปิด MT5 ต้นแบบ"},{title:"ดาวน์โหลดและติดตั้ง Worker",body:"ใช้บัญชี Windows สำหรับรัน MT5 โดยเฉพาะ เปิด PowerShell แล้วรันคำสั่งด้านล่าง ระบบจะถาม Runner ID, API URL และ Worker Key"},{title:"ตรวจการเชื่อมต่อแล้วเปิดรับลูกค้า",body:"คง Windows session ให้ล็อกอินอยู่ ตรวจ EA บนบัญชี Demo ก่อน จากนั้นเปิดรับงานในแท็บ VPS & MT5"}].map((step,i)=><div className={s.step} key={step.title}><span className={s.stepNumber}>{i+1}</span><div><b>{step.title}</b><p>{step.body}</p></div></div>)}</div><a className={`${s.button} ${s.primary}`} href="/downloads/SCENOVA-CloudWorker.ps1" download>↓ ดาวน์โหลด Cloud Worker</a><code className={s.code}>{'powershell.exe -ExecutionPolicy Bypass -File .\\SCENOVA-CloudWorker.ps1 -Install'}</code><p className={s.muted}>Worker เริ่มอัตโนมัติเมื่อบัญชี Windows นี้ล็อกอิน เครื่องต้องเปิดตลอดเวลา การตัด Remote Desktop ทำได้ แต่การ Sign out จะหยุดโปรแกรม</p></div></Panel>
      <Panel title="เชื่อม PromptPay" kicker="02 / PAYMENT GATEWAY"><div className={`${s.panelBody} ${s.form}`}><div className={s.inline}><b>Opn / Omise</b><Badge tone={data.paymentMode==="LIVE"?"good":"warn"}>{data.paymentMode}</Badge></div><p className={s.muted}>ตั้งค่ากุญแจฝั่ง API เท่านั้น เริ่มด้วย Test Key และทดสอบการจ่ายสำเร็จ ยอดไม่ตรง และ Webhook ซ้ำ ก่อนเปลี่ยนเป็น Live Key</p><code className={s.code}>{'OMISE_SECRET_KEY=ใส่ที่ระบบจัดเก็บความลับของเซิร์ฟเวอร์\nLOCAL_CHECKOUT_ENABLED=true\nCLOUD_CHECKOUT_ENABLED=true'}</code><label className={s.field}>Webhook URL<code className={s.code}>{typeof window!=="undefined"?window.location.origin:"https://your-domain"}/backend/api/payments/omise/webhook</code></label><p className={s.muted}>เลือกเหตุการณ์ charge.complete และ charge.create ระบบจะตรวจยอดจาก Gateway อีกครั้งก่อนเปิดสิทธิ์</p><form className={s.form} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save("/reconcile",{chargeId:f.get("chargeId")});}}><label className={s.field}>ตรวจรายการที่ Webhook ตกหล่น<input name="chargeId" placeholder="chrg_…" required pattern="chrg_[a-zA-Z0-9_]+"/></label><button disabled={busy} className={s.button}>ตรวจสอบกับผู้ให้บริการ</button></form><a href="https://docs.omise.co/promptpay" target="_blank" rel="noreferrer">เอกสาร PromptPay ↗</a></div></Panel></div>
      <div className={s.notice}>เมื่อชำระสำเร็จ ระบบเปิดสิทธิ์และจอง VPS ให้ ลูกค้าต้องเชื่อมบัญชี MT5 แล้วรอ EA ออนไลน์ จึงกด Start ได้ การชำระเงินจะไม่เริ่มเทรดเอง</div>
    </>}
    <div className={s.footer}><span>SCENOVA CLOUD · สถานะจากระบบจริง</span><span>อัปเดต {updated} · รีเฟรชอัตโนมัติทุก 15 วินาที</span></div>
  </div>;
}
function NodeCard({node:n,busy,save}:{node:Node;busy:boolean;save:(path:string,body:any)=>Promise<any>}) {
  const [capacity,setCapacity]=useState(n.capacity);
  const [accept,setAccept]=useState(n.accepting_jobs);
  return <section className={s.nodeCard}><div className={s.nodeHead}><div><h3>▤ {n.runner_id}</h3><span className={s.nodeMeta}>{n.region} · {n.hostname||"รอ Worker"}</span></div><Badge tone={n.health==="ONLINE"?"good":"warn"}>{n.health}</Badge></div><p className={s.nodeMeta}>{n.spec||"ยังไม่ระบุสเปก"} · ฿{money(n.monthly_cost*100)}/เดือน</p><div className={s.nodeLoad}><span>MT5 ใช้ / จอง</span><b>{Math.max(n.occupied,n.active_instances)} / {n.capacity}</b></div><div className={s.bar}><span style={{width:Math.min(100,Math.max(n.occupied,n.active_instances)/n.capacity*100)+"%"}}/></div><div className={s.telemetry}><div><small>CPU</small><b>{n.health==="ONLINE"&&n.telemetry?.cpuPercent!=null?n.telemetry.cpuPercent+"%":"—"}</b></div><div><small>RAM</small><b>{n.health==="ONLINE"&&n.telemetry?.ramUsedGb!=null?`${n.telemetry.ramUsedGb} / ${n.telemetry.ramTotalGb} GB`:"—"}</b></div></div><p className={s.muted}>ติดต่อครั้งล่าสุด {date(n.last_seen_at)}<br/>MT5 Template: {n.telemetry?.templateReady?"พร้อม":"รอตรวจสอบ"}</p><form className={s.form} onSubmit={e=>{e.preventDefault();save("/nodes/"+encodeURIComponent(n.runner_id),{capacity,acceptingJobs:accept});}}><div className={s.inline}><label className={s.field}>Capacity<input type="number" min={1} max={200} required value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label className={s.check}><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>รับลูกค้าใหม่</label></div><button disabled={busy} className={s.button}>บันทึกการตั้งค่า</button></form><p className={s.muted}>พักรับลูกค้าใหม่จะไม่หยุด MT5 ที่กำลังทำงาน</p></section>;
}
function PackageEditor({pack:p,busy,save,system="CLOUD"}:{pack:CloudPackage;busy:boolean;save:(path:string,body:any)=>Promise<any>;system?:"LOCAL"|"CLOUD"}) {
  const [price,setPrice]=useState(String(p.price_satang/100));const [enabled,setEnabled]=useState(p.enabled);
  return <form className={`${s.package} ${p.months===3?s.featured:""}`} onSubmit={e=>{e.preventDefault();save("/packages",{months:p.months,priceSatang:Math.round(Number(price)*100),enabled});}}><span className={s.eyebrow}>{system} MEMBERSHIP</span><h3>{p.months} เดือน</h3><Badge tone={p.enabled?"good":""}>{p.enabled?"เปิดขาย":"ยังไม่เปิดขาย"}</Badge><div className={s.features}><span>1 Cloud MT5</span><span>ควบคุมผ่านเว็บ / มือถือ</span><span>ต่ออายุเก็บเวลาที่เหลือ</span></div><label className={s.field}>ราคารวม (บาท)<input type="number" min={0} max={1000000} step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label className={s.check}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>เปิดขายแพ็กเกจนี้</label><button className={s.button} disabled={busy}>บันทึกแพ็กเกจ</button></form>;
}
