from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
import json
import re

SOURCE = Path("mt5/FastBasketBot.mq5")
PART_GLOB = "FastBasketBot.Part*.mqh"
PART_PREFIX = "FastBasketBot.Part"
TARGET_LINES = 1800
MIN_LINES = 1400
MAX_PARTS = 16
ANCHOR = "enum ENUM_ENTRY_MODE"
MANIFEST = Path("mt5/FastBasketBot.modules.json")


@dataclass
class ScanState:
    brace_depth: int = 0
    preproc_depth: int = 0
    block_comment: bool = False


def scan_line(line: str, state: ScanState) -> tuple[ScanState, bool]:
    stripped = line.lstrip()
    if not state.block_comment:
        if re.match(r"#\s*(if|ifdef|ifndef)\b", stripped):
            state.preproc_depth += 1
        elif re.match(r"#\s*endif\b", stripped):
            state.preproc_depth = max(0, state.preproc_depth - 1)

    i = 0
    in_string: str | None = None
    escaped = False
    while i < len(line):
        ch = line[i]
        nxt = line[i + 1] if i + 1 < len(line) else ""

        if state.block_comment:
            if ch == "*" and nxt == "/":
                state.block_comment = False
                i += 2
                continue
            i += 1
            continue

        if in_string is not None:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_string:
                in_string = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            break
        if ch == "/" and nxt == "*":
            state.block_comment = True
            i += 2
            continue
        if ch in ('"', "'"):
            in_string = ch
            i += 1
            continue
        if ch == "{":
            state.brace_depth += 1
        elif ch == "}":
            state.brace_depth -= 1
            if state.brace_depth < 0:
                raise RuntimeError("brace depth became negative")
        i += 1

    clean = line.strip()
    safe_end = (
        state.brace_depth == 0
        and state.preproc_depth == 0
        and not state.block_comment
        and not clean.endswith("\\")
        and (
            clean.endswith(";")
            or clean.endswith("}")
            or clean.startswith("#include")
            or clean.startswith("#define")
            or clean.startswith("#undef")
        )
    )
    return state, safe_end


def split_remainder(remainder: str) -> list[str]:
    lines = remainder.splitlines(keepends=True)
    parts: list[str] = []
    start = 0
    state = ScanState()

    for idx, line in enumerate(lines):
        state, safe_end = scan_line(line, state)
        count = idx + 1 - start
        if count >= TARGET_LINES and safe_end:
            parts.append("".join(lines[start : idx + 1]))
            start = idx + 1

    if start < len(lines):
        parts.append("".join(lines[start:]))

    if not parts:
        raise RuntimeError("no module parts produced")
    if len(parts) > MAX_PARTS:
        raise RuntimeError(f"too many generated parts: {len(parts)}")
    if len(parts) > 1 and any(len(p.splitlines()) < 200 for p in parts[:-1]):
        raise RuntimeError("unexpectedly tiny non-final module part")
    return parts


def expand_generated(root_text: str, part_map: dict[str, str]) -> str:
    out: list[str] = []
    include_re = re.compile(r'^#include\s+"(FastBasketBot\.Part\d{2}\.mqh)"\s*$')
    for line in root_text.splitlines(keepends=True):
        m = include_re.match(line.rstrip("\r\n"))
        if m:
            out.append(part_map[m.group(1)])
        elif line.startswith("// SCENOVA STRUCTURAL MODULES:"):
            continue
        elif line.startswith("// Runtime behavior is preserved"):
            continue
        elif line.startswith("// Generated by scripts/refactor-mq5-structural.py"):
            continue
        else:
            out.append(line)
    return "".join(out)


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"missing source: {SOURCE}")

    original = SOURCE.read_text(encoding="utf-8")
    if '#include "FastBasketBot.Part01.mqh"' in original:
        raise SystemExit("FastBasketBot.mq5 is already structurally modularized")

    anchor_at = original.find(ANCHOR)
    if anchor_at < 0:
        raise SystemExit(f"anchor not found: {ANCHOR}")

    header = original[:anchor_at]
    remainder = original[anchor_at:]

    required_header_tokens = [
        '#property strict',
        '#property version',
        '#define SCENOVA_EA_VERSION',
        '#define SCENOVA_PRODUCT_VERSION',
        '#define SCENOVA_RUNTIME_CONTRACT',
    ]
    for token in required_header_tokens:
        if token not in header:
            raise SystemExit(f"required header token would move out of root MQ5: {token}")

    parts = split_remainder(remainder)
    part_map: dict[str, str] = {}
    for index, content in enumerate(parts, start=1):
        name = f"{PART_PREFIX}{index:02d}.mqh"
        part_map[name] = content

    root_lines = [
        header,
        "// SCENOVA STRUCTURAL MODULES: order-preserving source partition only.\n",
        "// Runtime behavior is preserved byte-for-byte when these includes are expanded.\n",
        "// Generated by scripts/refactor-mq5-structural.py; do not reorder the parts.\n",
    ]
    for name in part_map:
        root_lines.append(f'#include "{name}"\n')
    root = "".join(root_lines)

    reconstructed = expand_generated(root, part_map)
    if reconstructed != original:
        raise RuntimeError("expanded modular source is not byte-for-byte identical to original")

    original_hash = sha256(original.encode("utf-8")).hexdigest()
    reconstructed_hash = sha256(reconstructed.encode("utf-8")).hexdigest()
    if original_hash != reconstructed_hash:
        raise RuntimeError("source hash changed after structural partition")

    for old in SOURCE.parent.glob(PART_GLOB):
        old.unlink()

    for name, content in part_map.items():
        (SOURCE.parent / name).write_text(content, encoding="utf-8")
    SOURCE.write_text(root, encoding="utf-8")

    manifest = {
        "format": "SCENOVA_ORDER_PRESERVING_MQ5_MODULES_V1",
        "source": str(SOURCE).replace("\\", "/"),
        "originalSha256": original_hash,
        "expandedSha256": reconstructed_hash,
        "originalLines": len(original.splitlines()),
        "rootLines": len(root.splitlines()),
        "parts": [
            {
                "file": f"mt5/{name}",
                "lines": len(content.splitlines()),
                "sha256": sha256(content.encode("utf-8")).hexdigest(),
            }
            for name, content in part_map.items()
        ],
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"Original lines: {manifest['originalLines']}")
    print(f"Root lines: {manifest['rootLines']}")
    print(f"Generated parts: {len(parts)}")
    print(f"Expanded SHA-256: {reconstructed_hash}")
    for item in manifest["parts"]:
        print(f"  {item['file']}: {item['lines']} lines")


if __name__ == "__main__":
    main()
